### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pamelafox** [carlsborg/rcviz#12]
I adapted your great library to make a recursion visualizer for my students at UC Berkeley. 
Source code @ 
https://github.com/pamelafox/recursive-visualizations
Usable @ https://www.recursionvisualizer.com/
I'm wondering if you can clarify the license of your repository, so that I can put an appropriate license on my repo? I currently link to your library on the website to give attribution, but I don't know if that's okay.
Thanks for the library!

**Comment by pamelafox** [comment]
Ah, sorry, I just realized the license was in the file:
http://www.gnu.org/licenses/gpl-2.0.html
I'll follow that, thanks!

**Comment by carlsborg** [comment]
Wow I am deeply humbled. Very nice to see what you have done with it.
